### ISSUE TITLE
Getting an error, kindly support

### ISSUE THREAD

**Issue by shareef009** [prashants/webzash-v1-defunct#10]
I have copied the package from GITHUB and while using i am getting this error, kindly support what to do.Thanks in advance.

---

A PHP Error was encountered

Severity: Warning

Message: mktime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Moscow' for '3.0/no DST' instead

Filename: helpers/date_helper.php

Line Number: 487

---

A PHP Error was encountered

Severity: Warning

Message: date(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Moscow' for '3.0/no DST' instead

Filename: helpers/MY_date_helper.php

Line Number: 101

---

**Comment by shareef009** [comment]
This one too ...

---

Security Risk ! The application config directory "config/" is world readable.
Security Risk ! The application accounts directory "config/accounts/" is world readable.
Security Risk ! The users directory "config/users/" is world readable.
Security Risk ! The application settings directory "config/settings/" is world readable.
Security Risk ! The application backup directory "backups/" is world readable.

---

**Comment by prashants** [comment]
For security risk check permission of the folders.

For date() can you add call to date_default_timezone_set() before the line numbers in error.

eg : date_default_timezone_set("Europe/Moscow");

http://www.w3schools.com/php/func_date_default_timezone_set.asp
http://www.php.net/manual/en/timezones.php

**Comment by prashants** [comment]
file : 

system/application/helpers/MY_date_helper.php

**Comment by shareef009** [comment]
Thanks for the prompt response, i am little confused about where to make the changes and what is the exact path for   "date_helper.php" file.

**Comment by prashants** [comment]
system/application/helpers/MY_date_helper.php

before
Line Number: 487
Line Number: 101

**Comment by shareef009** [comment]
By the way sorry to inform you that the permission are given to read and write.

**Comment by shareef009** [comment]
I guess i have to make changes in two files right ?

1) date_helper.php : i dont know the exact path (add "date_default_timezone_set("Europe/Moscow");" before line 487 ?)
2) MY_date_helper.php : system/application/helpers/MY_date_helper.php ( add "date_default_timezone_set("Europe/Moscow");" before line 101 ?)

**Comment by prashants** [comment]
yup

**Comment by prashants** [comment]
system/helpers/date_helper.php
system/application/helpers/MY_date_helper.php

**Comment by prashants** [comment]
system/helpers/date_helper.php : Line Number: 487
system/application/helpers/MY_date_helper.php : Line Number: 101

**Comment by shareef009** [comment]
1) MY_date_helper.php :
/*
case 'dd/mm/yyyy':
*\* date_default_timezone_set("Europe/Moscow"); **
return date('d M Y', $ts);
break;
*/

---

2) date_helper.php:
/*
}
*\* date_default_timezone_set("Europe/Moscow"); *\*  
return mktime($hour, $min, $sec, $month, $day, $year);
}

---

Is this ok ?

**Comment by shareef009** [comment]
Great it is working fine now, thanks a lot Sir .. i would like to know more in near future about this program because i have just started using it.So kindly support me. Thanks again

**Comment by prashants** [comment]
join the google group listed on website.

**Comment by shareef009** [comment]
I received one more error.

---

A PHP Error was encountered

Severity: Warning

Message: date(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Moscow' for '3.0/no DST' instead

Filename: helpers/MY_date_helper.php

Line Number: 125

---

A PHP Error was encountered

Severity: Warning

Message: date(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Moscow' for '3.0/no DST' instead

Filename: helpers/MY_date_helper.php

Line Number: 137

---

Do i require to do the same before these lines ?

**Comment by prashants** [comment]
Yes. Let me know if it works.

**Comment by shareef009** [comment]
It worked, i cant find the link for Google groups. I hope i should not receive any error now.

**Comment by prashants** [comment]
http://groups.google.com/group/webzash-help/
