### ISSUE TITLE
I received one more error

### ISSUE THREAD

**Issue by shareef009** [prashants/webzash-v1-defunct#11]
I received one more error.

---

A PHP Error was encountered

Severity: Warning

Message: date(): It is not safe to rely on the system's timezone settings. You are required to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Moscow' for '3.0/no DST' instead

Filename: helpers/MY_date_helper.php

Line Number: 125

---

A PHP Error was encountered

Severity: Warning

Message: date(): It is not safe to rely on the system's timezone settings. You are required to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Moscow' for '3.0/no DST' instead

Filename: helpers/MY_date_helper.php

Line Number: 137

---

Do i require to do the same before these lines ?

**Comment by prashants** [comment]
Solved here : https://github.com/prashants/webzash/issues/10
