### ISSUE TITLE
Issue in the amount for 32-bit platform

### ISSUE THREAD

**Issue by manuthalasseril** [prashants/webzash-v1-defunct#13]
When I enter an amount of 100000000(Ten crore/100 million) in 32 bit platform that creates problems.. When  I comment these lines
$param1 = $param1 \* 100;
$param2 = $param2 \* 100;   (line 210)
on the function 'float_ops' under 'custom_helper.php' in 'helpers', then it works smooth. 

When I upload on server there is no problem. .So I searched on google, says that its because of PHP int declaration. Actually why we convert these float values to int. whats the purpose behind it?

**Comment by prashants** [comment]
Because 12.23 is a float value and floating point computations are not accurate, they will give weird results like 12.23999999999 sometimes. So we multiply by 100 and then convert it to int - it will become 1233 (int) - do the math and then convert it back to 12.23 by dividing by 100.

**Comment by prashants** [comment]
Its a PHP internal limitations with int. Better option is to use a external math library like http://www.php.net/manual/en/intro.bc.php. I have not used that since many host don't support it.

**Comment by manuthalasseril** [comment]
thank you prashant...

**Comment by prashants** [comment]
New version of webzash is available at webzash.org. It uses bc math for calculations, it can support upto 23 digits numbers.
