### ISSUE TITLE
Problem in Chaning Accounts

### ISSUE THREAD

**Issue by bssridhar** [prashants/webzash-v1-defunct#14]
I recently installed Webzash.

I am unable to change the company i am working on.

I am able to create new account using :- 
Administer->Create Account->

The account is also created. When i select the particular account, its name alone changes but the transactions remain the same.

My requirement is I want Company 1 & Company 2 to work on.

Do i have to create a seperate database for every company i wish to create?

Kindly reply

**Comment by wqr786** [comment]
That's true I guess. But I've already automated this process on my end, in case you'd like to discuss more about it and see a Demo, please add me to Skype or Gtalk:
Skype: wqr786
Gtalk: waqar [@] 4acetech [dot] com

**Comment by prashants** [comment]
Company selection is saved in sessions. If you want to use two companies at the same time, use separate browsers like chrome and firefox so that session data is not shared. Hope this helps.
