### ISSUE TITLE
Problem in opening balance when I enter more than 21474836.48

### ISSUE THREAD

**Issue by keetawat** [prashants/webzash-v1-defunct#15]
Dear All,
Assets
       |_ Fixed Assets
                   |_Machinery and Equipment Ledger Account Dr 21474836.48 Cr 21474836.48

I have problem when I enter the value more than Dr 21474326.48  then Cr will be come change to un-balance on Cr Value.

Please help me.
thank you

**Comment by manuthalasseril** [comment]
That may be because of Int declaration of PHP. please follow this link https://github.com/prashants/webzash/issues/13

**Comment by prashants** [comment]
We are working on new version of webzash that will support math bc library. Please see the comment by manuthalasseril for temporary fix.

**Comment by prashants** [comment]
New version of webzash is available at webzash.org. It uses bc math for calculations, it can support upto 23 digits numbers.
