### ISSUE TITLE
Can i have accounts in single database ? rather than having seperate db for each account ?

### ISSUE THREAD

**Issue by ASHFAQSOLANGI** [prashants/webzash-v1-defunct#17]
Hello,
i want to use single db for all the accounts, means if i create 2 accounts in webzash
that must should use only single database, as currently each new account ask for the new database, kindly suggest

**Comment by prashants** [comment]
Will be hard to do. Check code igniter if you can add a database prefix. Since the model names are based on table names only way is to see if code igniter used with webzash can support database prefix.

**Comment by prashants** [comment]
New version of webzash is available at webzash.org. It supports table prefix so that you can have multiple accounts in a single database.
