### ISSUE TITLE
adding new feature

### ISSUE THREAD

**Issue by aInternational** [prashants/webzash-v1-defunct#19]
Hello,

I want to add description for each row on adding entry.
Would you mind help me how we can do it?

**Comment by prashants** [comment]
Hi,

You will have to modify database table "entry_items" and also change the corresponding controller and view :

https://github.com/prashants/webzash/blob/v1.x/system/application/controllers/entry.php
https://github.com/prashants/webzash/tree/v1.x/system/application/views/entry

**Comment by kjcpa** [comment]
You may use the Narration box.

**Comment by prashants** [comment]
User wants to add narration for each item in the entry. See my above comment. If you need further help please reopen the ticket.
