### ISSUE TITLE
Auto Activation

### ISSUE THREAD

**Issue by NewLion** [prashants/webzash-v1-defunct#2]
Ref: Invalid account database. Table "settings" missing.

NewLion:
I looked up (line 77 in) system/application/controllers/user.php. Since [account_name] is already stored in [user].ini, what is the easiest way to auto activate this [account] after log on? Basically, I want users with only one account to skip the Activate step as this is redundant and instead load their dashboard.

prashants:
after line 77 once the user is auth, get the user details from line 140. this will give you the account name in $active_user['accounts'] in string, convert to array in 150. if one element then line 180 to load the account. set session in 187 and then redirect to home page.
much more simple hack :
just add one line after line no. 77 where 'sample' is the account label. thats it.
$this->session->set_userdata('active_account', 'sample');

**Comment by NewLion** [comment]
OK, I've implemented and tested the auto activation feature. Here's the code for it to be added after line 77:

<pre>
if ($active_user['accounts'] != '*' and count (explode (',', $active_user['accounts'] )) == 1)
{
    $this->session->set_userdata('active_account', $active_user['accounts']);
}
</pre>


Everything is working fine now, except, I am still seeing from time to time "Invalid Entry type specified. Showing all Entries." error message when listing or creating a new entry. It is more visible for payment and contra, but not yet able to figure a pattern.

**Comment by prashants** [comment]
I will close this issue and open a new one for the Showing all Entries." error message

**Comment by prashants** [comment]
please check this issue https://github.com/prashants/webzash/issues/3
