### ISSUE TITLE
IS THIS PROJECT STILL OPEN?

### ISSUE THREAD

**Issue by mbsarino** [prashants/webzash-v1-defunct#23]
I notice there hasn't been much activity in the last year.  Is this project still running?

**Comment by prashants** [comment]
Yes ! We are working on a new version which will be lauched by this month end :) 

https://bitbucket.org/prashants/webzash

**Comment by wqr786** [comment]
@mbsarino: I wonder if you're looking for any services for this? I can help
if you want to deploy it somewhere or customize it or something. I have the
experience in working on this platform.

**Comment by mbsarino** [comment]
oh ok.  i would like to use webzash on Joomla 3.x and tried it with the
current version.  However, I ran into problems trying to use an SSO
component for Joomla as webzash apparently uses email addresses as
username.  is there a way for me to change that in the current version?

**Comment by prashants** [comment]
> webzash apparently uses email addresses as username

webzash uses username and not email address to login.

**Comment by prashants** [comment]
The authentication information is stored in text file in the config/users directory.

**Comment by mbsarino** [comment]
is there a way for me to use mysql to store the authentication info?

**Comment by prashants** [comment]
Not in the current version. The upcoming version is based on CakePHP and uses sqlite to store user info which can be changed to MySQL or whatever you want. If you are willing to wait for few days I can give you a full setup of the upcoming version - its almost 90% done.

**Comment by mbsarino** [comment]
great!  looking forward to it!

**Comment by prashants** [comment]
I will comment here with the link to download by coming monday.

**Comment by prashants** [comment]
Here is the full setup.

https://drive.google.com/file/d/0B1pQ4esmUnBeNHFyYTRvMjdFakU/edit?usp=sharing

There is a download icon on the top of the page above the white model box.

**Comment by mbsarino** [comment]
I have installed the new setup.  However, I still cannot find the users table on database.

**Comment by prashants** [comment]
Its a sqlite file in the app/Plugin/Webzash/Database/ folder.

**Comment by prashants** [comment]
If you want to change the auth db then check the  app/Plugin/Webzash/Config/bootstrap.php -> init_account() function.

This is the database schema

https://bitbucket.org/prashants/webzash/src/476eb100c492159fa0b4bac98d37e0117e0d2c03/Config/MasterSchema.Sqlite.sql?at=master

**Comment by prashants** [comment]
This is what you will have to substitute with : http://book.cakephp.org/2.0/en/development/configuration.html

**Comment by prashants** [comment]
If you find any bugs or issues comment here.

**Comment by mbsarino** [comment]
unfortunately, asi have previously mentioned, I am not a programmer so I
wouldn't know the specific steps to take. Would it be too much to ask for
you to send me the revised files/configuration?

Thanks!

**Comment by prashants** [comment]
What exactly are your requirements ?

**Comment by mbsarino** [comment]
Im looking fo an an online accounting app that our company can use and
include in its intranet.  Right now we are using Joomla 3.2 as the portal
and all apps on it are either Joomla extensions or 3rd party apps accessed
with a Joomla SSO utillity.

**Comment by prashants** [comment]
I will check and let you know. Which is the exact module that you are using ? There are few SSO's for Joomal out there.

**Comment by mbsarino** [comment]
I'm using Joomla 3.2 and JFusion 2.0
Sent from my BlackBerry® smartphone from Sinyal Bagus XL, Nyambung Teruuusss...!

-----Original Message-----

**Comment by prashants** [comment]
Ok. Since I am busy with the release what I can do is, look into this issue after the release. I will keep this open for now.

**Comment by vesper8** [comment]
Hi prashants,

I'm very excited about this new version you are refering to. Will it be released under this github page? I still don't see an update here or on webzash.org. Are you almost ready to release it? I would love to know what has changed and what new features are included.

Looking forward to hearing more

**Comment by prashants** [comment]
Will be releasing it next week end.

**Comment by mbsarino** [comment]
hi prashants,

Do you have the changelog/release notes for the new version?

**Comment by mbsarino** [comment]
hello prashants,

Have you released the new version yet?

**Comment by prashants** [comment]
Expect a beta this weekend :)

**Comment by prashants** [comment]
Beta version is available at

Download the TAR.GZ version below :
https://dl.dropboxusercontent.com/u/50842471/webzash-beta.tar.gz

Download the ZIP version below :
https://dl.dropboxusercontent.com/u/50842471/webzash-beta.zip

**Comment by mbsarino** [comment]
Hello Prashants!

Thanks for the link!  I was able to download and install it already.  However when I try to Adminisnister an account, it gives me a "Settings table is missing. Please check whether this is a valid account database".  I would assume after going through the setup process and filling in all blanks completely, the required tables for the database are automatically created.  Did I miss anything in the installation?

**Comment by prashants** [comment]
When do you get that error - when you activate an account or you are trying to add a account config from the administer section ?

**Comment by mbsarino** [comment]
I get it when I try to activate an account.

**Comment by prashants** [comment]
Did you use the setup link above and create a new account from scratch or you are using an existing account ? Also, did you get any errors while account creation ? Also please check whether the database details are correct. I tried the setup on my side and it works.

**Comment by mbsarino** [comment]
setup link where? its a totally new install.

**Comment by prashants** [comment]
https://github.com/prashants/webzash/issues/23#issuecomment-59640208

**Comment by prashants** [comment]
Beta version is available at

Download the TAR.GZ version below :
https://dl.dropboxusercontent.com/u/50842471/webzash-beta.tar.gz

Download the ZIP version below :
https://dl.dropboxusercontent.com/u/50842471/webzash-beta.zip

**Comment by mbsarino** [comment]
I downloaded from that link and unpacked the zip to my web directory

**Comment by prashants** [comment]
Ok. Please try creating account again and see if you get any error.

**Comment by prashants** [comment]
Also please check your database if the tables have been created. Its throwing that error since it cant find the db tables.

**Comment by mbsarino** [comment]
I checked the database the setup created and the tables that it is looking
for are actually there, although empty.

**Comment by prashants** [comment]
Do you see a row with id of 1 in the settings table ?

**Comment by mbsarino** [comment]
yes.  I did another clean install and I can activate it now.

**Comment by prashants** [comment]
Great.

**Comment by mbsarino** [comment]
Now I'm back to my original problem with the previous version:  where can I
find the users table, the one that holds the username and passwords field.
The "settings" table is apparently not the one that I need.

**Comment by prashants** [comment]
Its in the sqlite file. app/Plugin/Webzash/Database

**Comment by mbsarino** [comment]
thanks!

**Comment by mbsarino** [comment]
I apparently need to have the users database in the standard sql database
for me to access it from an external app.  Is there a way to do this?

**Comment by prashants** [comment]
If the external app supports sqlite then you can just provide the full sqlite path as database name and leave the username and password field empty.
1. Otherwise, create a new MySQL database with the schema shown at Webzash/Config / MasterSchema.Sqlite.sql
2. Open the Webzash/Config/bootstrap.php

Replace from line 313 to 317 with this

$wz['datasource']  = 'Database/Mysql';
$wz['persistent'] = false;
$wz['host'] = 'hostname';
$wz['login'] = 'username';
$wz['password'] = 'password';
$wz['database'] = 'dbname';
$wz['prefix'] = '';

**Comment by mbsarino** [comment]
Under the Webzash folder, I only have 4 directories: app, lib, plugins,
vendors and therefore can't find the path/files you refer to. Although
there is a Config directory in the Apps folder, the bootstrap.php file in
it contains just over 100 or so lines.

Also, I will need to edit the menu bar to remove the Webzash name and
change the bar color.  Which files would I need to edit these?

**Comment by prashants** [comment]
Webzash has been developed as a cakephp plugin. You will find all the files in app/Plugin/Webzash

**Comment by mbsarino** [comment]
Hello Prashants

I notice there are no provisions to be able to print any of the reports.  Are there plans to add this functionality?

**Comment by prashants** [comment]
Yes. That part will be done before final release.

**Comment by vesper8** [comment]
is there going to be a tutorial or docs to explain how to set this up for those of us not familiar with the old version and not familiar with the cake framework? I grabbed the beta from this thread and tried setting it up on nginx and I'm getting the first page but the css isn't loading. I've located the css but it's just unclear how to set up my vhost in order for the paths to load properly. I also looked for where the mysql tables generation script is but couldn't locate them. Is there an install.txt anywhere that explains all this stuff?

**Comment by prashants** [comment]
http://www.nginxtips.com/nginx-configuration-for-cakephp-framework/

I will have tutorials / wiki after the final release.

**Comment by mbsarino** [comment]
When is your final release slated for?

Sent from my BlackBerry® smartphone from Sinyal Bagus XL, Nyambung Teruuusss...!

-----Original Message-----

**Comment by prashants** [comment]
Nov end

**Comment by mbsarino** [comment]
i've tried importing the  MasterSchema.Sqlite.sql file into a blank
database but I get the following error:

"#1064 - You have an error in your SQL syntax; check the manual that
corresponds to your MySQL server version for the right syntax to use near
'"wzaccounts" ("id" INTEGER PRIMARY KEY NOT NULL, "label" VARCHAR NOT NULL,
"db_d' at line 1 "

Whaat do I need to do?

**Comment by mbsarino** [comment]
Hello Prashants,

Is there a solution to the issue on importning the MasterSchema.sql file
above?

**Comment by prashants** [comment]
I am checking it.

**Comment by prashants** [comment]
It seems sqlite and MySQL syntax are not compatible :(

**Comment by prashants** [comment]
Please try with this schema.

https://bitbucket.org/prashants/webzash/raw/f882576906d29080bd749e49b2400e790d197772/Config/MasterSchema.MySQL.sql

**Comment by prashants** [comment]
If you can wait I will be releasing a updated beta version in 2 days.

**Comment by mbsarino** [comment]
No prob. Ill wait. Thanks!!
Sent from my BlackBerry® smartphone from Sinyal Bagus XL, Nyambung Teruuusss...!

-----Original Message-----

**Comment by mbsarino** [comment]
Hi Prashants,

Any news on the updated beta version?

**Comment by mbsarino** [comment]
I replaced lines 313 to 317 as instructed but now, I get this error when I
setup:

_Warning_ (2): PDO::__construct(): php_network_getaddresses:
getaddrinfo failed: No such host is known.
[_CORE\Cake\Model\Datasource\Database\Mysql.php_, line _158_]

_\app\Plugin\Webzash\Config\bootstrap.php_ (line _326_)

'Missing master sqlite database file. Please check your setup.'

Let me know if I missed out on anything.

**Comment by prashants** [comment]
Sorry I am out of touch since last few days. I will get back to you next week.

**Comment by mbsarino** [comment]
Hi Prashant

Any updates on the new version and my SQL issue?

**Comment by prashants** [comment]
I will be available from monday onwards.

**Comment by mbsarino** [comment]
Hi Prashant,

Any updates on the new version and my sql problem?

**Comment by prashants** [comment]
I was not well since last few weeks. I am back now. I have restarted the work on webzash. Will update you soon.

**Comment by prashants** [comment]
Beta 2 version of Webzash-Next has been released.

Download the TAR.GZ version below :
https://www.dropbox.com/s/c6oe3z5vldu1j32/webzash-beta2.tar.gz?dl=0

Download the ZIP version below :
https://www.dropbox.com/s/bndxogrpal5wz9m/webzash-beta2.zip?dl=0

**Comment by prashants** [comment]
Hi,

The mysql script has been updated. Also the database config is now available at

app/Plugin/Webzash/Config/MasterConfig.php

Please make the changes there. Check the comments section in the same file. Sample MySQL config is available.

Also for the getaddrinfo error, try hostname as 127.0.0.1

**Comment by mbsarino** [comment]
Thanks Prashant!

Btw, is there an email address that I can reach you in private?  I'd like
to discuss a few things that may not be relevant to the rest of the group.

Thanks!

**Comment by prashants** [comment]
pshah.mumbai AT gmail

**Comment by prashants** [comment]
I am closing this issue for now since this repository is no longer active. Please open a new issues below for the Joomla integration if its still pending.

https://github.com/prashants/webzash/issues
