### ISSUE TITLE
how can i find users table in Webzash

### ISSUE THREAD

**Issue by fatimazaheer** [prashants/webzash-v1-defunct#28]

**Comment by prashants** [comment]
Which version V1.x or V2.x are you using ?

**Comment by fatimazaheer** [comment]
V2.x

**Comment by prashants** [comment]
Hi, it will better if you open a issue at https://github.com/prashants/webzash since this repo is for v1.x and is defunct and not in use.

To answer your query the user info is stored in sqlite 3 database in app/Plugin/Webzash/Database/webzash.sqlite

**Comment by fatimazaheer** [comment]
ok thanks

**Comment by prashants** [comment]
I am closing this issue. If you have any further queries kindly open a new issue at https://github.com/prashants/webzash
