### ISSUE TITLE
Where to change english month names to spanish month names

### ISSUE THREAD

**Issue by mytbi** [prashants/webzash-v1-defunct#29]
Hi, I was able to transalate to Spanish almost 99% using your instractions for translation. However, I can not find a way to show the spanish month names, for example:

Jan = ENERO
Feb = Febrero 
etc...
This is a great program, thank for  your help.

**Comment by prashants** [comment]
Please use the https://github.com/prashants/webzash repository. This is old defunct version which is no longer maintained.
