### ISSUE TITLE
Showing all Entries error message

### ISSUE THREAD

**Issue by prashants** [prashants/webzash-v1-defunct#3]
Everything is working fine now, except, I am still seeing from time to time "Invalid Entry type specified. Showing all Entries." error message when listing or creating a new entry. It is more visible for payment and contra, but not yet able to figure a pattern.

**Comment by prashants** [comment]
Can you add a screenshot for the message on http://imgur.com/

**Comment by NewLion** [comment]
I will try to post a screen shot. But basically, if payment or contra entry is selected, there is an error message in pink shown over the table of entries that say:

Invalid Entry type specified. Showing all Entries.

The error message seem a bit odd because, only the correct type of entries (payment or contra) are displayed in the table and their functionality seem to work as expected. Same error is visible during add of either of these two entry types, but it does not cause add to fail. Not seen the error during edit though.

**Comment by prashants** [comment]
Can you post the data dump of the entry_types table ? Maybe something is missing there. I suspect its something related to INSERT statements.

**Comment by NewLion** [comment]
Data dump of the entry_types table:

<pre>
 id | label   | name    | description                                        |base_type | numbering | prefix | suffix | zero_padding | bank_cash_ledger_restriction |
+----+---------+---------+----------------------------------------------------+----------+-----------+--------+--------+--------------+------------------------------+
|  1 | receipt | Receipt | Received in Bank account or Cash account           |        1 |         1 |        |        |            0 |    2                         |
|  2 | payment | Payment | Payment made from Bank account or Cash account     |        1 |         1 |        |        |            0 |    3                         |
|  3 | contra  | Contra  | Transfer between Bank account and Cash account     |        1 |         1 |        |        |            0 |    4                         |
|  4 | journal | Journal | Transfer between Non Bank account and Cash account |        1 |         1 |        |        |            0 |    5                         |
+----+---------+---------+----------------------------------------------------+----------+-----------+--------+--------+--------------+------------------------------+
4 rows in set (0.00 sec)
</pre>

**Comment by prashants** [comment]
Do you have a public IP where I can access the server ? I am not sure why are you getting that error message.

**Comment by NewLion** [comment]
OK, I will look in to code and try figure out the reason for the error. Will appreciate, if you can provide relevant pointers to help me in the process.

Thanks.

**Comment by prashants** [comment]
its in system/application/controllers/entry.php line number 46. 

can you add a var_dump($entry_type_id); after line number 43. you should get a id from the above table.
