### ISSUE TITLE
Calculation Issue

### ISSUE THREAD

**Issue by NewLion** [prashants/webzash-v1-defunct#5]
There seem to be a problem with calculations. Here's a test Trial Balance

<pre>
Ledger Account  O/P Balance     C/L Balance     Dr Total    Cr Total
Cash/Asset      Dr 30000.00     Dr 30000.00     0           0
Some Loan       Cr 2060.00      Dr 2060.00      0           0
Direct Expense1 Dr 5000.00      Dr 5000.00      0           0
Direct Income1  Cr 25000.00     Dr 25000.00     0           0
</pre>

Correct if I'm wrong, but without any transactions, shouldn't closing (C/L) balances for Loan and  Income1 be a Cr balance ?

Similarly, P&L is showing Net Loss of 30000 when it should be (Income - Expense = 25000 - 5000) Net Profit of 20000.

**Comment by prashants** [comment]
I am checking it. you are right there is some bug in the closing balance calculation.

**Comment by NewLion** [comment]
Let me know the changes required in my version to fix the bugs.

Thanks.

**Comment by prashants** [comment]
https://github.com/prashants/webzash/commit/0f175561428972ba6ebb299d6e19793d39267ec8

**Comment by NewLion** [comment]
Calculation error is fixed, but account creation is broken again:

 (in v1.5.3)

<pre>
Error creating account database. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-new' at line 1
</pre>


Possibly broken INSERT statement.

**Comment by prashants** [comment]
It is not a broken insert. It says 'Error creating account database.' There is some problem with create database. I have made lot of repo changes yesterday (not code changes). I suggest you delete the entire repo and clone it again. Always checkout the branch "v1.x". Those are the latest changes.

**Comment by NewLion** [comment]
I downloaded v1.x by clicking on: (https://github.com/prashants/webzash/zipball/v1.x) and then got that error. Just now however, I re-checked and found the problem: I was using a dash (-) in database name which caused the error. False alarm. My bad. It will be nice, if these checks are built-in, like checks for label. Also, I noticed not entering any opening balance (not even 0) during account creation throws several PHP errors. Again, built-in validations will be a nice touch.

One other thing: I am getting additional status messages now which probably do not apply to a Windows box. Suggest checking at code level to see if it is a Linux machine before throwing the following warnings:

Application settings directory "config/settings/" is not writable. You will not able to edit any application related settings.
Account settings directory "config/accounts/" is not writable. You will not able to add or edit any account related settings.
User directory "config/users/" is not writable. You will not able to add or edit any users.
Backup directory "backups/" is not writable. You will not able to save or download any backups.
Security Risk ! The application config directory "config/" is world readable.
Security Risk ! The application accounts directory "config/accounts/" is world readable.
Security Risk ! The users directory "config/users/" is world readable.
Security Risk ! The application settings directory "config/settings/" is world readable.
Security Risk ! The application backup directory "backups/" is world readable.

Thanks.

**Comment by prashants** [comment]
Also, I noticed not entering any opening balance (not even 0) during account creation throws several PHP errors. Again, built-in validations will be a nice touch.

I dont get these errors on a LAMP setup. Maybe I will try to get access to a Windows machine for testing. Also I will keep these things in mind.

Thanks for your feedback.

**Comment by NewLion** [comment]
Probably because different platforms treat initialization differently. Recommend forced initialization of important variables.

**Comment by prashants** [comment]
can you post your copy of the php.ini on http://pastebin.com/

**Comment by prashants** [comment]
"Also, I noticed not entering any opening balance (not even 0) during account creation throws several PHP errors. Again, built-in validations will be a nice touch."

I have fixed this issue for creating /editing ledger account in the latest v1.x branch.
